version: "3.9"

services:
  pg_database:
    container_name: cineprime_pg_database
    image: postgres:latest
    environment:
      POSTGRES_USER: cineprime
      POSTGRES_PASSWORD: cineprime
      POSTGRES_DB: cineprime_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    container_name: cineprime-backend
    image: cineprime-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3333:3333"
    environment:
      BACKEND_PORT: 3333
      DATABASE_URL: "postgres://cineprime:cineprime@cineprime_pg_database:5432/cineprime_db"
      JWT_SECRET: "40028922ehofunkdoiudiquevaidarplaystation2"
      CPF_CINEMA_OWNER: "81912063310"
    env_file:
      - backend/.env
    depends_on:
      - pg_database

  frontend:
    container_name: cineprime-frontend
    image: cineprime-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_PORT: 3333
    depends_on:
      - backend
      - pg_database
